# This is a basic workflow to help you get started with Actions

name: Latex Formatter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get list of changed .tex files
      id: tex_files
      run: |
        COMMIT_RANGE="${{ github.event.before }}...${{ github.event.after }}"
        TEX_FILES=$(git diff --name-only $COMMIT_RANGE | grep '\.tex$' || echo '')
        echo "files=$TEX_FILES" >> $GITHUB_OUTPUT

    - name: Install tex-fmt
      if: steps.tex_files.outputs.files != ''
      run: |
        # Update package list
        sudo apt-get update
        sudo apt-get install cargo
        sudo cargo install tex-fmt

    - name: Run tex-fmt on committed .tex files
      if: steps.tex_files.outputs.files != ''
      run: |
        for file in ${{ steps.tex_files.outputs.files }}; do
          # Run tex-fmt on each file (replace with the actual command)
          tex-fmt "$file"
        done
