# This is a basic workflow to help you get started with Actions

name: Python Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Linting
        uses: programmingwithalex/pylinter@main
        with:
          python-root: '.'
          flake8-flags: '--max-line-length=100 --ignore=E128'
          skip-mypy: true
          fail-on-isort: true
      - name: Python Black Formatter
        uses: cytopia/docker-black@0.8
        with:
          path: 'src/'
